# Generated by Django 4.1.7 on 2023-02-21 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import serverless.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workbook_json', models.JSONField(default=serverless.models.get_default_workbook)),
                ('revision', models.IntegerField(default=1)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverless.license')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=256, unique=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverless.license')),
            ],
        ),
    ]
