# Generated by Django 4.1.7 on 2023-02-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedomain',
            name='domain',
            field=models.CharField(max_length=256),
        ),
    ]
