# Generated by Django 4.1.7 on 2023-03-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serverless", "0002_alter_licensedomain_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="workbook",
            name="name",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="workbook",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
