# Generated by Django 4.1.7 on 2023-03-15 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serverless", "0003_workbook_name_workbook_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnsubscribedEmail",
            fields=[
                ("email", models.CharField(max_length=256, primary_key=True, serialize=False)),
                ("create_datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
