# Generated by Django 4.1.7 on 2023-03-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serverless", "0004_unsubscribedemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workbook",
            name="name",
            field=models.CharField(default="Book", max_length=256),
        ),
    ]
