# Generated by Django 4.1.7 on 2023-03-30 12:16

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def update_validated_datetime(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Updates the 'validated_datetime' on active licenses."""
    License = apps.get_model("serverless", "License")
    for license in License.objects.all():
        print(f"migrating {license}")
        if license.email_verified:
            print(f"..email verified")
            license.validated_datetime = license.create_datetime
            print(f"..setting license.validated_datetime = {license.create_datetime}")
            license.save()


class Migration(migrations.Migration):
    dependencies = [
        ("serverless", "0005_alter_workbook_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="validated_datetime",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.RunPython(update_validated_datetime),
    ]
