# Generated by Django 4.1.7 on 2023-04-19 16:05

from zoneinfo import ZoneInfo

import equalto
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils import timezone


def create_new_workbooks(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    License = apps.get_model("serverless", "License")
    Workbook = apps.get_model("serverless", "Workbook")
    create_dt = timezone.datetime(2023, 4, 19, 12, 0, 0, tzinfo=ZoneInfo("UTC"))
    for license in License.objects.all():
        print(f"creating new default workbook for {license}")
        # create a new workbook which can be used in the sample snippet
        workbook = Workbook.objects.create(
            license=license,
            workbook_json=equalto.load("serverless/data/Investment Growth Calculator.xlsx").json,
            create_datetime=create_dt,
        )
        workbook.name = "Investment Growth Calculator"
        workbook.save()


class Migration(migrations.Migration):
    dependencies = [
        ("serverless", "0006_license_validated_datetime"),
    ]

    operations = [
        migrations.RunPython(create_new_workbooks),
    ]
